version: 2

sources:

    - name: dbgen
#      database: db1
      schema: db1
      tags: ["dbgen"]
      # freshness:
      #   warn_after: {count: 12, period: hour}
      #   error_after: {count: 24, period: hour}
      # loaded_at_field: created_at
      loader: S3
      description: "External tables from OTUS S3"

      tables:

        - name: customer
          description: "Customers source in S3 bucket"
          identifier: src_customer

        - name: lineorder
          description: "lineorder source in S3 bucket"
          identifier: src_lineorder

        - name: part
          description: "parts source in S3 bucket"
          identifier: src_part

        - name: supplier
          description: "supplier source in S3 bucket"
          identifier: src_supplier